production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
staging:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= Rails.application.credentials.dig(:staging, :secret_key_base) %>