default:
  toolbar:
    - bold italic | removeformat | undo redo
  menubar: false
  entity_encoding : "raw"

displaytitle:
  toolbar:
    - italic | removeformat | undo redo 
  menubar: false
  forced_root_block: false
  entity_encoding : "raw"

pages:
  toolbar:
    - formatselect | bold italic strikethrough | link | alignleft aligncenter alignright alignjustify | image | numlist bullist outdent indent | table | removeformat | undo redo
  menubar:
    - file
  plugins:
    - image
    - link
    - table
    - media
    - hr
    - lists
    - advlist
    - media
    - fullscreen
    - preview
  image_advtab: true
  image_caption: true
  entity_encoding : "raw"
  relative_urls : false
  remove_script_host : true
  document_base_url : "https://jesuitonlinebibliography.bc.edu/"
  block_formats:
    'Paragraph=p;Heading 3=h3;Heading 4=h4;Heading 5=h5;Heading 6=h6;Address=address;Pre=pre'