default:
  toolbar:
    - bold italic | undo redo
  menubar: false

displaytitle:
  toolbar:
    - italic | undo redo
  menubar: false
  forced_root_block: false

pages:
  toolbar:
    - formatselect | bold italic strikethrough | link | alignleft aligncenter alignright alignjustify | image | numlist bullist outdent indent | table | removeformat | undo redo
  menubar:
    - file
  plugins:
    - image
    - link
    - table
    - media
    - hr
    - lists
    - advlist
    - media
    - fullscreen
    - preview
  image_advtab: true
  image_caption: true
  block_formats:
    'Paragraph=p;Heading 3=h3;Heading 4=h4;Heading 5=h5;Heading 6=h6;Address=address;Pre=pre'